import { createSlice } from "@reduxjs/toolkit";

let initialState = {
    isOpen : false
}

let modalSlice = createSlice({
    name: 'modal',
    initialState,
    reducers: {
        openModal: (state, action) => {
            state.isOpen = true
        },
        closeModal: (state, action) => {
            state.isOpen = false
        }
    }
})

export let {openModal, closeModal} = modalSlice.actions //openModal and closeModal are extracted from modalSlice.actions and exported. These can be used to dispatch actions in your application.
export default modalSlice.reducer //modalSlice.reducer is the reducer function generated by createSlice, which handles the openModal and closeModal actions. This reducer is exported as the default export and can be added to the Redux store.
